### ISSUE TITLE
🐛 Symlinked file not found in `/tmp/resting_preproc_sub-{sub}_ses-{ses}/func_gather_0/_scan_rest/selectrest`

### ISSUE THREAD

**Issue by shnizzedy** [shnizzedy/brainlife-C-PAC#1]
**Describe the bug**

```Python
Traceback (most recent call last):
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in run
    self, report_type='postexec', is_mapnode=isinstance(self, MapNode))
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 156, in write_report
    result = node.result  # Locally cache result
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 195, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 364, in load_resultfile
    **modify_paths(outputs, relative=False, basedir=path))
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 482, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 502, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /tmp/resting_preproc_sub-9002_ses-1/func_gather_0/_scan_rest/selectrest/bids/sub-9002/ses-1/func/sub-9002_ses-1_task-rest_bold.nii.gz not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 72, in run_node
    result['result'] = node.result
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 195, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 364, in load_resultfile
    **modify_paths(outputs, relative=False, basedir=path))
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 482, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 502, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /tmp/resting_preproc_sub-9002_ses-1/func_gather_0/_scan_rest/selectrest/bids/sub-9002/ses-1/func/sub-9002_ses-1_task-rest_bold.nii.gz not found
```

**To Reproduce**
1. try to run this repository on Brainlife

OR

1. Clone this repository
2. Locally recreate the Brainlife directory structure
3. Run `./main`

**Expected behavior**

C-PAC runs the default pipeline on the single subject in `bids`.

**Versions** 
 - C-PAC: v1.7.0
 - Container Platform :
    - Singularity: 2.5.2-HEAD.b258b6514

**Additional context**

Brainlife uses [bl2bids](https://github.com/brainlife/abcd-spec/blob/master/hooks/bl2bids) to create a local directory called `bids` that looks like this
```tree
├── bids
│   ├── dataset_description.json
│   └── sub-9002
│       └── ses-1
│           ├── anat
│           │   ├── sub-9002_ses-1_T1w.json
│           │   └── sub-9002_ses-1_T1w.nii.gz -> ../../../../../5f185b023f121164d2bf5080/5d797315b0578272dd90df95/t1.nii.gz
│           └── func
│               ├── sub-9002_ses-1_task-rest_bold.json
│               └── sub-9002_ses-1_task-rest_bold.nii.gz -> ../../../../../5f185b023f121164d2bf5080/5e546c4b5b9d90232672dae5/bold.nii.gz
```

**Comment by shnizzedy** [comment]
Related: https://github.com/FCP-INDI/cpac_run_logs/issues/1

**Comment by shnizzedy** [comment]
> A couple debugging updates:
> 1. Running locally, `bl2bids` was creating symlinks with too many `..`s, so the links existed, but they didn't point to the correct path. I may have just set up my local incorrectly, though.
> 2. I think I have identified the underlying issue. C-PAC is/was checking for regular files but not symlinks, thus raising the error we've been seeing. I tried running a version of `bl2bids` locally that hardlinks instead of symlinks, and it seems to be avoiding those errors. I've got a C-PAC image [building now](https://app.circleci.com/pipelines/github/FCP-INDI/C-PAC/428/workflows/96a50a80-0f7c-4e1a-b35e-65d02c93e3a6/jobs/2606) that should resolve the symlinks so you don't have to change `bl2bids` to get C-PAC to work (unless [1] above is a real issue). I'll try this locally after it builds and let you know how it goes.

— [me ![on Slack](https://cdn.brandfolder.io/5H442O3W/at/pl546j-7le8zk-6gwiyo/Slack_Mark.png?width=12&height=12)](https://brainlife.slack.com/archives/CQC1G7VGT/p1597166191004800)

**Comment by shnizzedy** [comment]
Here's what `bids` looks like with hardlinks:

```tree
bids/
├── dataset_description.json
└── sub-9002
    └── ses-1
        ├── anat
        │   ├── sub-9002_ses-1_T1w.json
        │   └── sub-9002_ses-1_T1w.nii.gz
        └── func
            ├── sub-9002_ses-1_task-rest_bold.json
            └── sub-9002_ses-1_task-rest_bold.nii.gz
```

**Comment by shnizzedy** [comment]
[That fix](https://github.com/FCP-INDI/C-PAC/commit/63b159be6228089124a23393d68d5c51371546c0) didn't resolve it…

```Python
Nipype version 1.1.2
Traceback (most recent call last):

  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)

  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)

  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)

  File "/home/jon/.local/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/home/jon/.local/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)

  File "/code/CPAC/utils/interfaces/function.py", line 152, in _run_interface
    out = function_handle(**args)

  File "/code/CPAC/utils/datasource.py", line 494, in check_for_s3
    raise IOError('File {0} does not exist!'.format(local_path))

OSError: File bids/sub-9002/ses-1/func/sub-9002_ses-1_task-rest_bold.nii.gz does not exist!
```

**Comment by shnizzedy** [comment]
Update:

with this debugging setup:

https://github.com/shnizzedy/C-PAC/blob/d7507c3/CPAC/utils/datasource.py#L434-L459


this is what logs at the relevant step:
```
1. One
bids/sub-9002/ses-1/func/sub-9002_ses-1_task-rest_bold.nii.gz
is link? False
exists? False
2. Two
bids/sub-9002/ses-1/func/sub-9002_ses-1_task-rest_bold.nii.gz
is link? False
exists? False
3. Three
bids/sub-9002/ses-1/func/sub-9002_ses-1_task-rest_bold.nii.gz
is link? False
exists? False
```

**Comment by shnizzedy** [comment]
Partially resolved by [converting relative paths to absolute in positional arguments given to `run`](https://github.com/shnizzedy/C-PAC/commit/2c43c47b7fa99b9adc7b4f34bf789e8e38308972)

**Comment by shnizzedy** [comment]
This issue seems to be resolved

**Comment by shnizzedy** [comment]
As in [the original description of the issue here](#issue-675149041), running the default pipeline seems to have some path confusion.

```Python
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in run
    self, report_type='postexec', is_mapnode=isinstance(self, MapNode))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 156, in write_report
    result = node.result  # Locally cache result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 195, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 364, in load_resultfile
    **modify_paths(outputs, relative=False, basedir=path))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 482, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 502, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f724bff79a30b1258ed491d/5f724c0079a30b7676ed4920/output/working/resting_preproc_sub-A00021039_ses-DS2/func_gather_0/_scan_CHECKERBOARD/selectrest/bids/sub-A00021039/ses-DS2/func/sub-A00021039_ses-DS2_task-CHECKERBOARD_bold.nii.gz not found
```

`/N/dc2/scratch/brlife/carbonate-workflows/5f724bff79a30b1258ed491d/5f724c0079a30b7676ed4920/` is the directory C-PAC is being run from, and `/N/dc2/scratch/brlife/carbonate-workflows/5f724bff79a30b1258ed491d/5f724c0079a30b7676ed4920/bids/sub-A00021039/ses-DS2/func/sub-A00021039_ses-DS2_task-CHECKERBOARD_bold.nii.gz` exists, as does `/N/dc2/scratch/brlife/carbonate-workflows/5f724bff79a30b1258ed491d/5f724c0079a30b7676ed4920/output/working/resting_preproc_sub-A00021039_ses-DS2/func_gather_0/_scan_CHECKERBOARD/selectrest/`, but `bids` isn't inside `selectrest` which is where Nipype seems to want it.

Possibly related:
https://github.com/FCP-INDI/C-PAC/issues/1301, https://github.com/FCP-INDI/C-PAC/issues/1338, https://github.com/FCP-INDI/C-PAC/issues/1362 (all thrown by multiproc, maybe resolved when we finish Nipype upgrade)

**Comment by shnizzedy** [comment]
This error is consistently occurring with each subject I've tried:

<details>
<summary>NKI sub-A00021039</summary>
<pre><code>exception calling callback for <Future at 0x2ab323f2d790 state=finished raised OSError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in run
    self, report_type='postexec', is_mapnode=isinstance(self, MapNode))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 156, in write_report
    result = node.result  # Locally cache result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 195, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 364, in load_resultfile
    **modify_paths(outputs, relative=False, basedir=path))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 482, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 502, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f724bff79a30b1258ed491d/5f724c0079a30b7676ed4920/output/working/resting_preproc_sub-A00021039_ses-DS2/func_gather_0/_scan_CHECKERBOARD/selectrest/bids/sub-A00021039/ses-DS2/func/sub-A00021039_ses-DS2_task-CHECKERBOARD_bold.nii.gz not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 72, in run_node
    result['result'] = node.result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 195, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 364, in load_resultfile
    **modify_paths(outputs, relative=False, basedir=path))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 482, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 502, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f724bff79a30b1258ed491d/5f724c0079a30b7676ed4920/output/working/resting_preproc_sub-A00021039_ses-DS2/func_gather_0/_scan_CHECKERBOARD/selectrest/bids/sub-A00021039/ses-DS2/func/sub-A00021039_ses-DS2_task-CHECKERBOARD_bold.nii.gz not found
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f724bff79a30b1258ed491d/5f724c0079a30b7676ed4920/output/working/resting_preproc_sub-A00021039_ses-DS2/func_gather_0/_scan_CHECKERBOARD/selectrest/bids/sub-A00021039/ses-DS2/func/sub-A00021039_ses-DS2_task-CHECKERBOARD_bold.nii.gz not found</code></pre>
</details>
<details>
<summary>NKI sub-A00008326</summary>
<pre><code>exception calling callback for <Future at 0x2b0d995f52d0 state=finished raised OSError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in run
    self, report_type='postexec', is_mapnode=isinstance(self, MapNode))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 156, in write_report
    result = node.result  # Locally cache result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 195, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 364, in load_resultfile
    **modify_paths(outputs, relative=False, basedir=path))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 482, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 502, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f74826279a30bb10aeda60e/5f74826379a30b425feda611/output/working/resting_preproc_sub-A00008326_ses-DS2/func_gather_0/_scan_rest/selectrest/bids/sub-A00008326/ses-DS2/func/sub-A00008326_ses-DS2_task-rest_bold.nii.gz not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 72, in run_node
    result['result'] = node.result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 195, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 364, in load_resultfile
    **modify_paths(outputs, relative=False, basedir=path))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 482, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 502, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f74826279a30bb10aeda60e/5f74826379a30b425feda611/output/working/resting_preproc_sub-A00008326_ses-DS2/func_gather_0/_scan_rest/selectrest/bids/sub-A00008326/ses-DS2/func/sub-A00008326_ses-DS2_task-rest_bold.nii.gz not found
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f74826279a30bb10aeda60e/5f74826379a30b425feda611/output/working/resting_preproc_sub-A00008326_ses-DS2/func_gather_0/_scan_rest/selectrest/bids/sub-A00008326/ses-DS2/func/sub-A00008326_ses-DS2_task-rest_bold.nii.gz not found</code></pre>
</details>
<details>
<summary>NKI sub-A00028606</summary>
<pre><code>exception calling callback for <Future at 0x2b3d78aca350 state=finished raised OSError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in run
    self, report_type='postexec', is_mapnode=isinstance(self, MapNode))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 156, in write_report
    result = node.result  # Locally cache result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 195, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 364, in load_resultfile
    **modify_paths(outputs, relative=False, basedir=path))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 482, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 502, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f7482c379a30b5a65eda615/5f7482c379a30b6131eda618/output/working/resting_preproc_sub-A00028606_ses-DS2/func_gather_0/_scan_rest/selectrest/bids/sub-A00028606/ses-DS2/func/sub-A00028606_ses-DS2_task-rest_bold.nii.gz not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 72, in run_node
    result['result'] = node.result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 195, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 364, in load_resultfile
    **modify_paths(outputs, relative=False, basedir=path))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 482, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 502, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f7482c379a30b5a65eda615/5f7482c379a30b6131eda618/output/working/resting_preproc_sub-A00028606_ses-DS2/func_gather_0/_scan_rest/selectrest/bids/sub-A00028606/ses-DS2/func/sub-A00028606_ses-DS2_task-rest_bold.nii.gz not found
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f7482c379a30b5a65eda615/5f7482c379a30b6131eda618/output/working/resting_preproc_sub-A00028606_ses-DS2/func_gather_0/_scan_rest/selectrest/bids/sub-A00028606/ses-DS2/func/sub-A00028606_ses-DS2_task-rest_bold.nii.gz not found</code></pre>
</details>
<details>
<summary>NKI sub-A00028177</summary>
<pre><code>exception calling callback for <Future at 0x2b55e8d3e990 state=finished raised OSError>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 482, in run
    self, report_type='postexec', is_mapnode=isinstance(self, MapNode))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 156, in write_report
    result = node.result  # Locally cache result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 195, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 364, in load_resultfile
    **modify_paths(outputs, relative=False, basedir=path))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 482, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 502, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f7482ea79a30b2744eda61c/5f7482ea79a30b0095eda61f/output/working/resting_preproc_sub-A00028177_ses-DS2/func_gather_0/_scan_rest/selectrest/bids/sub-A00028177/ses-DS2/func/sub-A00028177_ses-DS2_task-rest_bold.nii.gz not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 72, in run_node
    result['result'] = node.result
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 195, in result
    return _load_resultfile(self.output_dir(), self.name)[0]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 364, in load_resultfile
    **modify_paths(outputs, relative=False, basedir=path))
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 482, in modify_paths
    val, relative=relative, basedir=basedir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 502, in modify_paths
    raise IOError('File %s not found' % out)
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f7482ea79a30b2744eda61c/5f7482ea79a30b0095eda61f/output/working/resting_preproc_sub-A00028177_ses-DS2/func_gather_0/_scan_rest/selectrest/bids/sub-A00028177/ses-DS2/func/sub-A00028177_ses-DS2_task-rest_bold.nii.gz not found
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 143, in _async_callback
    result = args.result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
OSError: File /N/dc2/scratch/brlife/carbonate-workflows/5f7482ea79a30b2744eda61c/5f7482ea79a30b0095eda61f/output/working/resting_preproc_sub-A00028177_ses-DS2/func_gather_0/_scan_rest/selectrest/bids/sub-A00028177/ses-DS2/func/sub-A00028177_ses-DS2_task-rest_bold.nii.gz not found</code></pre>
</details>
